#server.port=8000
#
#spring.datasource.url=jdbc:postgresql://localhost:2345/postgres
#spring.datasource.username=postgres
#spring.datasource.password=qwerty
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/postgres
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


