#server.port=8000
#
#spring.datasource.url=jdbc:postgresql://localhost:2345/postgres
#spring.datasource.username=postgres
#spring.datasource.password=qwerty
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/postgres?autoreconnect=true
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update