apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-deployment
spec: 
    replicas: 2
    selector:
        matchLabels:
            app: taskapp
    template:
        metadata:
            labels:
                app: taskapp
        spec:
            containers:
            -name: taskservicecontainer
                image: snega/task-microservice
                ports:
                - containerPort: 8005
                env:
                - name: SERVER_PORT
                    value: "8005"
                - name: SPRING_DATASOURCE_URL
                    value: "jdbc:postgresql://192.168.0.131:2345/postgres"
                - name: SPRING_DATASOURCE_USER
                    value: "postgres"
                - name: SPRING_DATASOURCE_PASSWORD
                    value: "qwerty"
                - name: USER_FEIGN_CLIENT_URL
                    value: http://