version: '3.6'
services:

  userdb:
    image: 'postgres'
    container_name: 'user-db'
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 2345:5432
    volumes:
      - userdb-data:/var/lib/postgresql/data

  taskdb:
    image: 'postgres'
    container_name: 'task-db'
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 2346:5432
    volumes:
      - taskdb-data:/var/lib/postgresql/data


  minio:
    image: minio/minio:latest
    container_name: 'minio_container'
    ports:
      - "9000:9000" #minio api
      - "9090:9090" # web interface
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address ":9090" /data

  minio-db:
    image: 'postgres'
    container_name: 'minio_db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - 2347:5432


  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://keycloak-db/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: qwerty
    command:
      - start-dev
      - --http-relative-path=/auth
    ports:
      - 8081:8080
      - 8843:8843
    depends_on:
      - keycloak-db

  keycloak-db:
    image: 'postgres:14'
    container_name: 'keycloak-db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - 2348:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data


volumes:
  userdb-data:
  taskdb-data:
  minio-data:
  minio_storage:
  pgdata:
