#feign.user.url=http://localhost:8000/
#server.port=8001
server:
  port: 8000

minio:
  url: http://localhost:9000
  user: admin
  password: adminadmin
  bucket: file-server-bucket


spring:
  datasource:
    url: jdbc:postgresql://localhost:2346/postgres
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 5MB
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

keycloak:
  url: http://localhost:8081/auth
  realm: bitlab-dev
  client-id: user-service-client
  client-secret: V2ICgxlZD3EtN1bpDrSKp5uz6eq2Pil4
  username: admin123
  password: admin123
  grant-type: password

feign:
  user:
    url: http://localhost:8001
