#feign.user.url=http://localhost:8000/
#server.port=8001
server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:2346/postgres
#    url: jdbc:postgresql://localhost:2346/taskdb
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

feign:
  user:
    url: http://localhost:8001
